import Shell from '@/components/Shell';
import { sb, getSession, canSeeFinancials } from '@/lib/session';
import { createAsset } from '@/lib/actions';

export const dynamic = 'force-dynamic';

export default async function NewAsset({
  searchParams,
}: { searchParams: { error?: string } }) {
  const session = await getSession();
  const supabase = sb();

  const [{ data: locs }, { data: models }, { data: types }] = await Promise.all([
    supabase.from('locations').select('id, name, kind').is('archived_at', null).order('name'),
    supabase.from('models').select('id, name, brands ( name ), sub_categories ( name )').order('name'),
    // Category and type for things that are not in the catalog. Without this
    // the fast path — which is now the normal path, since a model is optional
    // — produces assets nobody can group, filter or report on.
    supabase.from('sub_categories').select('id, name, categories ( name )').order('name'),
  ]);

  // No tag is suggested any more. It is generated by app.next_asset_tag() when
  // the field is left blank, which is the same rule the spreadsheet import
  // follows — previously the form demanded a tag the import was happy to
  // invent, so the same asset was accepted one way and refused the other.
  const warehouse = (locs ?? []).find((l: any) => l.kind === 'virtual');

  return (
    <Shell current="assets" title="Add an asset" subtitle="One at a time — use Import for a spreadsheet">
      {searchParams.error && <div className="notice bad"><p>{searchParams.error}</p></div>}

      <form action={createAsset}>
        <div className="card" style={{ marginBottom: 18 }}>
          <div className="card-h bd">
            <div>
              <div className="card-t">What it is</div>
              <div className="card-s">
                Linking it to a catalog model means it inherits the specification, service
                interval and warranty term — and it appears in maintenance automatically
              </div>
            </div>
          </div>
          <div style={{ padding: 20, display: 'grid', gap: 16 }}>
            <div>
              <label className="lbl" htmlFor="name">Name <span className="req">required</span></label>
              <input className="inp" id="name" name="name" required autoFocus
                     placeholder="e.g. Perkins 100 kVA generator" />
              <div className="hint">The only thing this form insists on.</div>
            </div>

            <div>
              <label className="lbl" htmlFor="description">Description</label>
              <textarea className="inp" id="description" name="description" rows={2}
                        placeholder="What somebody would need to recognise it — finish, size, condition, where it came from" />
            </div>

            <div style={{ display: 'grid', gap: 16, gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))' }}>
              <div>
                <label className="lbl" htmlFor="quantity">Quantity</label>
                <input className="inp" id="quantity" name="quantity" type="number"
                       min={1} max={100} step={1} defaultValue={1} />
                <div className="hint">
                  How many you have. Each one is created as its own asset with its own tag,
                  so they can be moved, repaired and disposed of separately. Over 100, use
                  Import — it previews the batch before committing it.
                </div>
              </div>
              <div>
                <label className="lbl" htmlFor="serial">Serial number</label>
                <input className="inp mono" id="serial" name="serial" placeholder="Leave blank if it has none" />
                <div className="hint">
                  Many things have none, and it can be filled in later by anyone. Only for a
                  quantity of one — a serial identifies a single machine.
                </div>
              </div>
            </div>

            <div>
              <label className="lbl" htmlFor="tag">Asset tag</label>
              <input className="inp mono" id="tag" name="tag" placeholder="Generated for you if left blank" />
              <div className="hint">
                Leave it blank and one is issued in your company&rsquo;s sequence. Fill it in only
                if you already label things your own way.
              </div>
            </div>

            <div>
              <label className="lbl" htmlFor="sub_category">Category and type</label>
              <select className="inp" id="sub_category" name="sub_category" defaultValue="">
                <option value="">Not classified</option>
                {(types ?? []).map((t: any) => (
                  <option key={t.id} value={t.id}>
                    {t.categories?.name ? `${t.categories.name} → ` : ''}{t.name}
                  </option>
                ))}
              </select>
              <div className="hint">
                Ignored if you pick a catalog model below — the model carries the
                classification, so the two can never disagree.
              </div>
            </div>

            <div>
              <label className="lbl" htmlFor="model">Catalog model</label>
              <select className="inp" id="model" name="model">
                <option value="">Not in the catalog</option>
                {(models ?? []).map((m: any) => (
                  <option key={m.id} value={m.id}>
                    {m.brands?.name ? `${m.brands.name} ` : ''}{m.name}
                    {m.sub_categories?.name ? ` · ${m.sub_categories.name}` : ''}
                  </option>
                ))}
              </select>
              {(models ?? []).length === 0 && (
                <div className="hint">
                  Nothing in the catalog yet. You can add this asset without one and link it
                  later — <a href="/catalog" style={{ textDecoration: 'underline' }}>set the catalog up</a>.
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="card" style={{ marginBottom: 18 }}>
          <div className="card-h bd">
            <div><div className="card-t">Where it is</div><div className="card-s">And who has it</div></div>
          </div>
          <div style={{ padding: 20, display: 'grid', gap: 16, gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))' }}>
            <div>
              <label className="lbl" htmlFor="location">Location</label>
              <select className="inp" id="location" name="location">
                <option value="">
                  {warehouse ? `Not sure yet — hold it in ${warehouse.name}` : 'Not sure yet'}
                </option>
                {(locs ?? []).map((l: any) => (
                  <option key={l.id} value={l.id}>{l.name}{l.kind === 'virtual' ? ' (virtual warehouse)' : ''}</option>
                ))}
              </select>
              <div className="hint">
                Leaving this blank puts it in the virtual warehouse, which is what that
                location is for. An asset in the wrong place is easier to correct than one
                never entered.
              </div>
            </div>
            <div>
              <label className="lbl" htmlFor="holder">Assigned to</label>
              <input className="inp" id="holder" name="holder" placeholder="Person, team or room" />
            </div>
            <div>
              <label className="lbl" htmlFor="acquired">Acquired on</label>
              <input className="inp" id="acquired" name="acquired" type="date" />
            </div>
            <div>
              <label className="lbl" htmlFor="meter">Meter reading</label>
              <div style={{ display: 'flex', gap: 8 }}>
                <input className="inp" id="meter" name="meter" type="number" step="any" placeholder="0" />
                <select className="inp" name="meter_unit" style={{ width: 110 }}>
                  <option value="">—</option>
                  <option value="hours">hours</option>
                  <option value="km">km</option>
                </select>
              </div>
              <div className="hint">Only for metered things — generators, vehicles.</div>
            </div>
          </div>
        </div>

        {canSeeFinancials(session) && (
          <div className="card" style={{ marginBottom: 18 }}>
            <div className="card-h bd">
              <div>
                <div className="card-t">What it cost</div>
                <div className="card-s">Stored separately, and only visible to roles that may see it</div>
              </div>
            </div>
            <div style={{ padding: 20, display: 'grid', gap: 16, gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))' }}>
              <div>
                <label className="lbl" htmlFor="cost">Purchase cost, each</label>
                <input className="inp" id="cost" name="cost" placeholder="e.g. 1,480,000" />
                <div className="hint">
                  The cost of one, not the invoice total. Ten chairs on a ₦450,000 invoice
                  are ₦45,000 each — depreciation and book value are worked out per asset.
                </div>
              </div>
              <div>
                <label className="lbl" htmlFor="invoice">Invoice reference</label>
                <input className="inp" id="invoice" name="invoice" />
              </div>
            </div>
          </div>
        )}

        <div style={{ display: 'flex', gap: 10 }}>
          <a className="btn btn-g" href="/assets">Cancel</a>
          <button className="btn btn-p" type="submit" style={{ marginLeft: 'auto' }}>Add to the register</button>
        </div>
      </form>
    </Shell>
  );
}
